apiVersion: apps/v1
kind: Deployment # what to create?
metadata:
  name: node-service-deployment
spec: # specification for deployment resource
  replicas: 1 # how many replicas of pods we want to create
  selector:
    matchLabels:
      app: node-service
  template: # blueprint for pods
    metadata:
      labels:
        app: node-service # service will look for this label
    spec: # specification for pods
      containers:
        - name: node-service
          image: piseumo/node-service
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: node-service