#apiVersion: v1
#kind: Namespace
#metadata:
#  name: maria-name
---
apiVersion: apps/v1
kind: Deployment # what to create?
metadata:
  name: mariadb-order-deployment
#  namespace: maria-name
spec: # specification for deployment resource
  replicas: 1 # how many replicas of pods we want to create
  selector:
    matchLabels:
      app: mariadb-order
  template: # blueprint for pods
    metadata:
      labels:
        app: mariadb-order # service will look for this label-order
    spec: # specification for pods
      containers:
        - name: mariadb-order
          image: mariadb
          ports:
            - containerPort: 33306 #default one
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: password
          volumeMounts:
            - name: mariadb-initdb-config-order
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mariadb-initdb-config-order
          configMap:
            name: mariadb-initdb-config-order
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-order
#  namespace: maria-name
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30307
  selector:
    app: mariadb-order